### ISSUE TITLE
What to do in Wiesbaden

### ISSUE THREAD

**Issue by habermannlh** [githubschool/github-managers-brianamarie#13]
Opelbad 🏊 
Wilhemstrassenfest 🎉 
Rheingauer Weinwoch 🍷 
Becker's Weingarten (Rheingau) 🍷 
Weihnachtsmarkt 🎄

**Comment by dergessi** [comment]
@habermannlh Kommst Du auch aus Wiesbaden?

**Comment by habermannlh** [comment]
@dergessi Ja, Du auch? Dein Gesicht kommt mir auch irgendwie bekannt vor, aber ich weiss nicht woher.
