### ISSUE TITLE
Parking Lot

### ISSUE THREAD

**Issue by beardofedu** [githubschool/github-managers-brianamarie#19]
- [x] Find resources for moving from Word documents to Markdown
- https://word-to-markdown.herokuapp.com/
- http://www.writage.com/

**Comment by brianamarie** [comment]
- [ ] Any data on average branch life or commits per pr?

**Comment by brianamarie** [comment]
- [ ] How much should go in one repository or one branch?

**Comment by brianamarie** [comment]
https://word-to-markdown.herokuapp.com/
