### ISSUE TITLE
Tuesday Lunch

### ISSUE THREAD

**Issue by brianamarie** [githubschool/github-managers-brianamarie#2]
[The menu can be found here](http://pizzeria-metaponto.de/wp-content/uploads/2017/01/FlyerMetaponto_11-2016_WebVersion.pdf). Please comment with your lunch number and your name 🍕 🍝 

<img width="855" alt="screen shot 2018-03-13 at 9 52 39 am" src="https://user-images.githubusercontent.com/9906718/37331474-5674f292-26a4-11e8-8471-45326272e463.png">
<img width="858" alt="screen shot 2018-03-13 at 9 52 56 am" src="https://user-images.githubusercontent.com/9906718/37331476-57705416-26a4-11e8-9637-6579b810d105.png">

**Comment by UFI68** [comment]
Do you have a link to The Menu List please ? ;)
Udo

**Comment by brianamarie** [comment]
@UFI68 Yep, I've uploaded and added it to the original post. ✨

**Comment by UFI68** [comment]
27 Insalata Italia - Udo Fischer

**Comment by habermannlh** [comment]
28 Insalata Tonno - Leonie Habermann

**Comment by Jesschusd** [comment]
30 Insalata Pollo - Jessica Schusdziarra

**Comment by saprsam** [comment]
Sampada Sapre - Number 1
Tsveta Angelova - Number 101

**Comment by migul1** [comment]
Michael Gulin -> # 18
Axel Bradschetl -> # 18

**Comment by scampijoe** [comment]
Oliver Albert - go for #10 (pizza Siciliana)

**Comment by beardofedu** [comment]
Matt - 36

**Comment by dergessi** [comment]
Marcus #14
Roel #6

**Comment by PatrycjaRz** [comment]
Patrycja #59

**Comment by BBahnemann** [comment]
Bastian -> #17 Pizza Hawaii

**Comment by kokiDBG** [comment]
32

**Comment by rashmikp27** [comment]
Nothing for me-Thanks

**Comment by UFI68** [comment]
Allerbeste Grüße
Udo Fischer

**Comment by beardofedu** [comment]
@migul1 👋

**Comment by beardofedu** [comment]
@brianamarie
