### ISSUE TITLE
QA repo

### ISSUE THREAD

**Issue by training99** [githubschool/github-managers-brianamarie#52]
- **Description:** QA repository

Hi Briana, Mat,

thx for the very useful github or non-developers training.

Since I do not know how to contact you in GitHub, I open an issue.

You asked what happens when we deliver software to our QA group. I said that the delivered tags are copied from the development repository to a 2nd respo, the QA repo. You asked why QA does not use protected branches and why 2nd repo is used. I said, I don't know, possibly because they used always their own repo, also with previous revision control systems.

I asked today a colleage from QA and he said that git / github does now allow to protect a tag and developers can modify a tag after it is delivered to QA. This is not audit save, therefore they copy the delivered tags to the QA repo which has r/w access for QA but not for developers.

I hope this answers your question.

Kind regards,
Juergen

**Comment by brianamarie** [comment]
Hello @training99! I am seeing this in lunch, and want to let you know I'll get you a fuller answer later and that I've seen this.

**Comment by training99** [comment]
Leave a comment

**Comment by training99** [comment]
Information given, issue will be closed.
